### PR TITLE
Compile groovy script once instead of every time

### PR DESCRIPTION
**Pull request by Jimilian**
Hi!
First of all, thanks you for your plugin!

In this PR I added some performance improvement. Now script will be compiled only once. Also class loaded is static now. So, it contains some cached data to make compilation faster next time.

p.s. Why did you add `synchronized` to `safeExecGroovyCode`? I'm going to remove it, but I didn't try it yet. So, it's interesting to know reasons.

### CODE REVIEW

**Comment by nickgrealy** [comment]
Hi @Jimilian,

Thanks for your contribution, the changes look good - just check the JenkinsTest.java, the test is [failing on the build server](https://jenkins.ci.cloudbees.com/job/plugins/job/groovy-events-listener-plugin/7/console) with `The page does not contain the text 'Groovy Code'`.

I added `synchronized` because I wasn't sure how Jenkins would be invoking the plugin, and I wanted to ensure it was being called in a thread safe manner. IMO it's a minor performance overhead, but if you can give me a compelling case for change, I'm happy for it to be removed.

Thanks,
Nick

**Comment by Jimilian** [comment]
@nickgrealy I failed to fix this test case. I checked configuration page on Jenkins and it works. In test environment it fails silently. And the most weird thing - test was ok several days ago. So, I decided to remove this flaky test.

@nickgrealy Performance overhead for `synchronize` itself is very low, I agree with you. Main problem was that all job threads in master are waiting each other at this point - for every (`onFinalize`, `onStart`, `onStart`) event in every build. So, if you have 10 threads, 9 threads will wait while the one will finish his onFinalize event. Of course, it happens only if event was called for 10 threads in same time.
In this plugin we was spending 90% of time in groovy compilation and only 10% in script. So, after this PR we have only 10%. I didn't investigate a better solution yet, because this one works, but you can add disclaimer that code inside groovy listener plugin should return access extremely fast :)

**Comment by nickgrealy** [comment]
@Jimilian, cool, well that's a good enough reason for me. Thinking about it, If anyone requires thread synchronisation, they could always just implement it themselves (rather than having it forced upon them!).

Did you want to remove they `synchronize` modifier, and update the README with a "disclaimer that code inside groovy listener plugin should return access extremely fast"? I'm happy to do it, but I thought you might like the credit for it?

Eitherway, I'm happy to merge this pull request, and push a new release. Let me know if/when you're ready.

**Comment by Jimilian** [comment]
@nickgrealy, yes, I think you can merge this PR if it works fine for you. I had tested it on my Jenkins, my college had tested it in staging environment, it works fine for us. But your plugin is too powerful to test all cases.
Please, add information about `synchronisation` to readme. I saw that you already made some changes in your local version, so, I don't want to create conflict here :) 

I'm pretty new with all this groovy + bindings magic, So, I don't know that's the best option to make execution thread-safe and avoid "everytime" compilation. I'm still investigating it.

Btw, is it possible to add [JMH](http://openjdk.java.net/projects/code-tools/jmh/) framework to dependencies ([gradle project](https://github.com/melix/jmh-gradle-plugin))? I just want to add visibility for performance changes.

**Comment by nickgrealy** [comment]
@Jimilian, change merged, version 1.010 released. Give it (up to) 24hours before the new version is available for download from the central Jenkins Plugin servers. I also squeezed a couple of other minor changes in -> https://github.com/jenkinsci/groovy-events-listener-plugin/issues?q=milestone%3A1.010

RE: JMH Framework - sounds great, except I don't know how to use it (never heard of it before). If you're willing to show me how to set it up, I'd be glad to add it.

Thanks!

**Pull request merged**
