### PR TITLE
Add posibility to add custom folders to classpath

### PR DESCRIPTION
**Pull request by Jimilian**

### CODE REVIEW

**Comment by nickgrealy** [comment]
Looks good! Any tests for the classpath?

**Comment by Jimilian** [comment]
It doesn't have any business logic except comma-separated splitting. Probably, you are right, and I can write several simple functional tests for this stuff.

**Comment by Jimilian** [comment]
@nickgrealy Could you check it? And if it's ok, merge and release new version?

**Comment by nickgrealy** [comment]
Checked, merged, and new version released. Thanks!

**Pull request merged**
