### PR TITLE
Add scheduler

### PR DESCRIPTION
**Pull request by Jimilian**
Now it's possible to setup plugin to execute script every minute (or less frequently).
It's quite useful if you want to push queue size, executors load or something like that from Jenkins.

### CODE REVIEW

**Comment by Jimilian** [comment]
@nickgrealy, is it ok for you?

**Comment by nickgrealy** [comment]
Yep. Had a look last night, looks simple and clean. Nice! 

Want me to merge and publish a new version?

**Comment by Jimilian** [comment]
Yes,  it would be great!

**Comment by Jimilian** [comment]
Tomorrow I'm going to add new feature -> add paths for classloader. It will make possible importing groovy classes from disk. Right now we are using workaround:
```groovy
this.getClass().getClassLoader().addClasspath('/var/lib/jenkins/groovy_scripts/');
this.getClass().getClassLoader().loadClass("com.companyname.ClassName");
def coolStats = new com.companyname.ClassName(run); // This line starts to work only after success execution of previous one
```
But it's not very user-friendly. So, I decided to add one extra field for advanced users -> classPaths and force plugin to load this classes to plugin.

**Pull request merged**
